backend:
  name: github
  repo: Mikeyouf/naturom
  branch: main
  commit_messages:
    create: "Creation de {{collection}} “{{slug}}”"
    update: "Mise à jour de {{collection}} “{{slug}}”"
    delete: "Mit à la corbeille: {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] mit à jour “{{path}}”"
    deleteMedia: "[skip ci] effacé “{{path}}”"

# Uncomment local_backend when you need to develop in your local
#local_backend: true # run npx netlify-cms-proxy-server for local testing

media_folder: "static/assets"
public_folder: "/assets"

collections:
  - name: "posts" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Posts" # Used in the UI
    label_singular: "Post" # Used in the UI, ie: "New Post"
    description: >
      Crée tes articles ici
    folder: "src/content/posts"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: "{{title}} — {{year}}/{{month}}/{{day}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {
          label: "Template",
          name: "template",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Titre", name: "title", widget: "string", tagname: "h1" }
      - {
          label: "Nom de l'url",
          name: "slug",
          widget: "string",
          hint: "TOUJOURS commencer avec /. Utiliser uniquement des caractères alpha-numérique, - et _. AUCUN espace entre les lettres ou mots.",
        }
      - {
          label: "Date de publication",
          name: "date",
          widget: "datetime",
          dateFormat: "YYYY-MM-DD",
          timeFormat: "HH:mm",
          format: "YYYY-MM-DD HH:mm",
        }
      - {
          label: "Description pour les moteurs de recherche",
          name: "description",
          widget: "text",
        }
      - {
          label: "Image de présentation",
          name: "featuredImage",
          widget: "image",
          required: false,
          tagname: "",
        }

      - {
          label: "Article",
          name: "body",
          widget: "markdown",
          hint: "Le principal de l'article se trouve ici.",
        }
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home"
        name: "home"
        file: "src/content/pages/index.md"
        fields:
          - {
              label: "Template",
              name: "template",
              widget: "hidden",
              default: "index-page",
            }
          - { label: "Slug", name: "slug", widget: "hidden", default: "/" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Tagline", name: "tagline", widget: "string" }
          - { label: "Featured Image", name: "featuredImage", widget: "image" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "CTA"
            name: "cta"
            widget: "object"
            fields:
              - name: "ctaText"
                label: "CTA text"
                widget: "string"
              - name: "ctaLink"
                label: "CTA Link"
                widget: "string"
      - label: "About"
        name: "about"
        file: "src/content/pages/about.md"
        fields:
          - {
              label: "Template",
              name: "template",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Slug", name: "slug", widget: "hidden", default: "/about" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Contact"
        name: "contact"
        file: "src/content/pages/contact.md"
        fields:
          - {
              label: "Template",
              name: "template",
              widget: "hidden",
              default: "contact-page",
            }
          - {
              label: "Slug",
              name: "slug",
              widget: "hidden",
              default: "/contact",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
  - name: settings
    label: Settings
    files:
      - name: general
        label: General
        file: "src/util/site.json"
        fields:
          - label: meta
            name: meta
            widget: object
            fields:
              - widget: string
                name: title
                label: Site Title
                required: true
              - widget: string
                name: titleTemplate
                label: Title Template
                default: "%s"
                required: true
              - widget: string
                name: siteUrl
                label: Website URL
                required: true
              - widget: text
                name: description
                label: Description
                default: ""
                required: false
              - widget: image
                name: image
                label: image
                default: "/assets/stackrole.png"
              - widget: string
                name: twitterUsername
                label: Twitter
                required: false

          - label: "Google Analytics"
            name: ga
            widget: string
            hint: "Add you tracking ID, for example UA-XXXXXXXXX-X"
